// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// LogDetDerChol
NumericVector LogDetDerChol(const Eigen::MatrixXd L, const Eigen::MatrixXd S, const Eigen::MatrixXd X, const Eigen::VectorXd mu, const Eigen::VectorXd wt, double tau);
RcppExport SEXP cox_LogDetDerChol(SEXP LSEXP, SEXP SSEXP, SEXP XSEXP, SEXP muSEXP, SEXP wtSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    __result = Rcpp::wrap(LogDetDerChol(L, S, X, mu, wt, tau));
    return __result;
END_RCPP
}
// VariationalVar
NumericVector VariationalVar(const Eigen::MatrixXd cholV, const Eigen::MatrixXd S);
RcppExport SEXP cox_VariationalVar(SEXP cholVSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type cholV(cholVSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type S(SSEXP);
    __result = Rcpp::wrap(VariationalVar(cholV, S));
    return __result;
END_RCPP
}
// VariationalVarIndep
NumericVector VariationalVarIndep(const Eigen::VectorXd diagV, const Eigen::MatrixXd S);
RcppExport SEXP cox_VariationalVarIndep(SEXP diagVSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type diagV(diagVSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type S(SSEXP);
    __result = Rcpp::wrap(VariationalVarIndep(diagV, S));
    return __result;
END_RCPP
}
// VariationalScore
Eigen::MatrixXd VariationalScore(const Eigen::VectorXd mu, const Eigen::VectorXd wt, double tau, const Eigen::VectorXd v, const Eigen::MatrixXd V, const Eigen::MatrixXd S);
RcppExport SEXP cox_VariationalScore(SEXP muSEXP, SEXP wtSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP VSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type S(SSEXP);
    __result = Rcpp::wrap(VariationalScore(mu, wt, tau, v, V, S));
    return __result;
END_RCPP
}
// VariationalScoreLogV
Eigen::MatrixXd VariationalScoreLogV(const Eigen::VectorXd mu, const Eigen::VectorXd wt, double tau, const Eigen::VectorXd v, const Eigen::MatrixXd V, const Eigen::MatrixXd S);
RcppExport SEXP cox_VariationalScoreLogV(SEXP muSEXP, SEXP wtSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP VSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type S(SSEXP);
    __result = Rcpp::wrap(VariationalScoreLogV(mu, wt, tau, v, V, S));
    return __result;
END_RCPP
}
