# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
LogDetDerChol <- function(L, S, X, mu, wt, tau) {
    .Call('cox_LogDetDerChol', PACKAGE = 'cox', L, S, X, mu, wt, tau)
}

VariationalVar <- function(cholV, S) {
    .Call('cox_VariationalVar', PACKAGE = 'cox', cholV, S)
}

VariationalVarIndep <- function(diagV, S) {
    .Call('cox_VariationalVarIndep', PACKAGE = 'cox', diagV, S)
}

VariationalScore <- function(mu, wt, tau, v, V, S) {
    .Call('cox_VariationalScore', PACKAGE = 'cox', mu, wt, tau, v, V, S)
}

VariationalScoreLogV <- function(mu, wt, tau, v, V, S) {
    .Call('cox_VariationalScoreLogV', PACKAGE = 'cox', mu, wt, tau, v, V, S)
}

